content/vendor/_index.md
Fixes https://github.com/replicatedhq/kots.io/issues/52
=> Fixed default link for vendor applications (#1)

content/kots-cli/admin-console.md, content/kots-cli/download.md, content/kots-cli/install.md, content/kots-cli/pull.md, content/kots-cli/reset-password.md, content/kots-cli/upload.md, content/kots-cli/upstream.md
Updated all the kots cli commands. I did my best with what information I had, but it needs technical validation for some commands (notably 'kots upload')
=> Adding usage/flags information for the kots cli

content/vendor/entitlements/creating-entitlements.md
Modzy let us know that our javascript syntax is incorrect. 
https://replicated.slack.com/archives/CSJDXGV0E/p1580235989054000
=> Fixing incorrect entitlements javascript

README.md, config.yaml, content/release-notes/1.10.0.md, content/release-notes/1.11.0.md, content/release-notes/1.11.1.md, content/release-notes/1.11.2.md, content/release-notes/1.11.3.md, content/release-notes/1.11.4.md, content/release-notes/1.9.0.md, content/release-notes/1.9.1.md, resources/_gen/assets/scss/scss/style.scss_5ad6f408b0e3e473c748aac88af0ea18.content, themes/hugo-whisper-theme/assets/scss/components/_title.scss, themes/hugo-whisper-theme/assets/scss/pages/_home.scss, themes/hugo-whisper-theme/layouts/_default/li.html, themes/hugo-whisper-theme/layouts/_default/list.html, themes/hugo-whisper-theme/layouts/_default/single.html, themes/hugo-whisper-theme/layouts/partials/sidebar.html, themes/hugo-whisper-theme/layouts/shortcodes/changes.html, themes/hugo-whisper-theme/layouts/shortcodes/features.html, themes/hugo-whisper-theme/layouts/shortcodes/fixes.html, themes/hugo-whisper-theme/layouts/shortcodes/notes.html
```bash
$ hugo new release-notes/<version>.md
```
=> Release Notes for KOTS

content/reference/template-functions/static-context.md
=> {{ repl Namespace }}

content/release-notes/1.12.1.md
Improving 1.12.1 release notes a bit
=> Improving 1.12.1 release notes a bit

content/vendor/quickstart/create-release.md, content/vendor/quickstart/install.md, content/vendor/quickstart/iterate.md, themes/hugo-whisper-theme/layouts/_default/list.html
Removing redundant titles from quickstart
=> Removing redundant titles

content/release-notes/1.13.4.md
diffs:
https://github.com/replicatedhq/kots/compare/v1.13.3...v1.13.4
https://github.com/replicatedhq/kotsadm/compare/v1.13.3...v1.13.4
=> 1.13.4 release notes

content/release-notes/1.13.3.md, content/release-notes/1.13.4.md, content/release-notes/1.13.5.md
=> Improving the last three release notes

content/vendor/packaging/ingress.md
Reverts replicatedhq/kots.io#138
=> Revert "Ingress IsKurl switched for embedded and existing clusters"

content/vendor/guides/_index.md, content/vendor/guides/production-ready.md
This guide starts out an outline for which features should be implemented to make a KOTS applications ready for production.
There are some sections commented/missing for now. I'd like to wait to pull those in until we have additional Guides finished (which I've outlined in guides/_index.md).
=> Basic guide for "best practices" and preparing to ship

content/kotsadm/updating/patching-with-kustomize.md
Had a few small tweaks, let me know what you think?
=> couple tweaks to kustomize guide

content/vendor/guides/ci-cd-integration.md
First pass ready for review.
Related `kotsapps` PR https://github.com/replicatedhq/kotsapps/pull/27
=> Ci/CD Integration guide

CONTRIBUTING.md
These are carried over and edited a touch from the Replicated Help Center style guides.
=> Add a contributing and style guide

content/reference/v1beta1/application.md, content/vendor/config/application-status.md
This reverts commit 7ea3210fef1e520ea373f43f760128b7b8e44150.
=> Revert "conditional status informers (#244)"

content/kots-cli/install.md, content/kots-cli/pull.md, content/kotsadm/installing/online-install.md
docs for https://github.com/replicatedhq/kots/issues/770
=> [1.18.0] installing behind a proxy docs

content/reference/template-functions/contexts.md, content/reference/template-functions/license-context.md
this will need to wait for kots 1.20
=> [v1.20.0] add IsAirgap, Sequence, ReleaseNotes template functions

content/reference/template-functions/static-context.md
Added in 1.17.0 - https://github.com/replicatedhq/kots/pull/695
=> Document the 'NodeCount' template function

content/vendor/snapshots/overview.md
updates to the styling change we made to k8s compatibility chart recently. makes the chart easier to maintain because we only need to update when we change valero versions vs each kots release
=> update compatibility chart style

content/kotsadm/snapshots/snapshot-types.md
Now that we separated vendor/admin content more, it's helpful to bring a bit of the "what is this" overview content to this page. I anticipate this page will become our overview page in subsequent docs iterations.
=> add some intro text

content/kotsadm/registries/self-hosted-registry.md, content/vendor/packaging/template-functions.md
Would love to get these minor changes approved.
=> Fixed a spelling error and minor quote character change

content/kotsadm/installing/helm-chart.md, content/vendor/packaging/rbac.md
Depends on  https://github.com/replicatedhq/kots.io/pull/388
=> Fix Bundle typos

content/kotsadm/installing/online-install.md
=> document license sync behavior for internet connected installs

content/vendor/guides/quickstart.md
(and some automatic whitespace adjustments)
=> Swap incorrect 'you'll' for 'you'

content/kotsadm/installing/system-requirements.md
Added firewall requirements based on [this thread](https://replicated.slack.com/archives/C9845152R/p1612555118343400).
Adding something similar in Kurl as well https://github.com/replicatedhq/kurl.sh/pull/344
=> add firewall requirements

content/kots-cli/get.md
=> [1.30.0] get backups & restores commands

config.yaml, content/kots-cli/_index.md, content/kots-cli/getting-started.md, content/kots-cli/pull.md, content/kotsadm/access/admin-console-roles.md, content/kotsadm/installing/airgap-packages.md, content/kotsadm/installing/online-install.md
Changed a number of Kots references to KOTS references.
=> Changed Kots to KOTS

content/kotsadm/updating/updating-embedded-cluster.md, content/kotsadm/updating/updating-kots-apps.md
=> [1.34.0] Updating kots apps in embedded clusters using the cli

content/kots-cli/velero/configure-aws-s3.md, content/kots-cli/velero/configure-azure.md, content/kots-cli/velero/configure-gcp.md, content/kots-cli/velero/configure-hostpath.md, content/kots-cli/velero/configure-internal.md, content/kots-cli/velero/configure-nfs.md, content/kots-cli/velero/configure-other-s3.md, content/kotsadm/snapshots/disaster-recovery.md, content/kotsadm/snapshots/storage-destinations.md
Reverts replicatedhq/kots.io#453
=> [ 1.38.0 ] add cli commands for snapshot storage config

content/vendor/guides/airgapped-cluster.md
Update wording for airgapped-cluster instructions to specify from which system to run commands.
=> - Update airgapped-cluster ssh tunnel instructions

content/kots-cli/admin-console/_index.md, content/kots-cli/admin-console/push-images.md, content/kots-cli/admin-console/upgrade.md
Added `admin-console push-images` command and grouped `admin-console` commands into a folder.
=> admin-console image-push command

content/kots-cli/getting-started.md, content/kotsadm/enterprise-cli/getting-started.md, content/vendor/cli/getting-started.md
I tested the non-privileged instructions and they work. TBH I didn't test the Windows ones but having done Windows development before I'm much more confident.
=> update windows support policy

content/kotsadm/snapshots/storage-destinations.md, content/vendor/packaging/rbac.md
minimal rbac with snapshots was asked about, and minimal rbac and how to make use of ensure-permissions command wasn't already covered in docs
=> add mention of minimal rbac steps

content/kots-cli/reset-tls.md
Adding doc for reset-tls command
=> [1.42.0] Create reset-tls.md

content/vendor/helm/helm-processing.md
=> [1.43.0] Updating Helm V3 Support Info

content/kots-cli/velero/configure-internal.md
Per convo @divolgin and I were having clarifying use of minio, this was incorrect as-is. Fixing.
=> remove incorrect minio reference

Makefile
@jdewinne this is the PR for removing `wget` and adding`curl`
=> Removed wget in favor of curl

content/kots-cli/docker/_index.md, content/kots-cli/docker/ensure-permissions.md, content/kotsadm/registries/dockerhub-rate-limiting.md
=> [1.44.0] Docker Hub rate limiting docs

content/vendor/packaging/ingress.md
Wally / Dex suggested wording update (from customer feedback)
=> ingress wording improvement

content/kots-cli/get/_index.md, content/kots-cli/get/apps.md, content/kots-cli/get/backups.md, content/kots-cli/get/restores.md
=> add kots get subcommands

content/reference/v1beta1/backup.md, content/release-notes/1.9.0.md, content/vendor/guides/persistent-datastores.md, content/vendor/packaging/include-resources.md, content/vendor/packaging/ingress.md, content/vendor/packaging/optional-resources.md, content/vendor/snapshots/configuring-backup.md
I have added the "placeholder" annotation to the reference documentation. 
Hopefully, I got the syntax correct, but I will need extra eyeballs on that (since I could not find any documentation on it).
This was requested by Wallaroo.
=> Added the 'placeholder' annotation to the reference guide.

content/release-notes/1.50.2.md, content/release-notes/1.51.0.md
=> [ 1.50.2 ] Release Notes

content/vendor/cli/tokens.md
[SH37221](https://app.shortcut.com/replicated/story/37221/update-api-token-documents)
=> docs: service account tokens

.github/workflows/update-release-notes.yaml, hack/release-notes.md.tmpl
Should be triggered when we tag for the pre-release.
=> Release Notes Action

content/vendor/entitlements/creating-entitlements.md
Fixed a minor wording issue and changed some formatting for clarity.
=> Changed response to request and minor formatting

content/vendor/packaging/promoting-releases.md
Reverts replicatedhq/kots.io#611
=> Revert "Document semver behavior"

content/kotsadm/gitops/multi-app-workflows.md, content/kotsadm/gitops/single-app-workflows.md
Shortcut: https://app.shortcut.com/replicated/story/41650/fix-broken-gitops-screenshots-links
=> 41650: Fixing broken links to images

content/release-notes/1.65.0.md
=> release notes for kots 1.65.0

themes/hugo-whisper-theme/assets/scss/pages/_home.scss, themes/hugo-whisper-theme/layouts/_default/baseof.html, themes/hugo-whisper-theme/layouts/partials/new-docs-banner.html
=> add deprecated banner

README.md
SC: https://app.shortcut.com/replicated/story/44477/add-notice-to-the-kots-io-readme
=> Adds guidance for where to update kots docs

README.md
Shortcut: https://app.shortcut.com/replicated/story/44978/update-the-kots-io-readme
Removed outdated Readme info.
=> Removed outdated content
