replicatedhq/kots.io

- config.yaml
- resources/_gen/assets/scss/scss/style.scss_5ad6f408b0e3e473c748aac88af0ea18.content
- themes/hugo-whisper-theme/assets/scss/components/_main-menu.scss
- themes/hugo-whisper-theme/layouts/partials/main-menu.html
At present, the section the user is currently in is not highlighted by the menu bar. This PR fixes that.
> Ensure currently activated section has been highlighted

- content/kotsadm/editing-ingress.md
- content/kotsadm/kotsadm-architecture.md
- content/kotsadm/merging-multiple-apps.md
- content/kotsadm/multiple-downstreams.md
- content/kotsadm/registries/self-hosted-registry.md
- content/kotsadm/zerotrust-management.md
- content/reference/_index.md
- content/reference/v1beta1/_index.md
- content/vendor/airgap.md
- content/vendor/licenses-and-release-channels.md
- content/vendor/promote-releases-cli.md
- themes/hugo-whisper-theme/layouts/_default/list.html
- themes/hugo-whisper-theme/layouts/partials/sidebar.html
The "redirect" argument was used in the _index.md files to indicate what should happen when you click the sidebar link for a section (e.g., so that clicking "Packaging an App" would take user to /vendor/packaging/packaging-an-app instead of the blank /vendor/packaging). 
This is a problem because having an _index.md file prevents using aliasing. That is, there was no way to then create an alias for /vendor/packaging because there was a direct page there. 
To fix this, I modified the list.html layout to do the exact same thing than an alias does (a meta redirect/refresh) when a "redirect" parameter exists. This way, we don't need to alias /vendor/packaging -- it just behaves properly. Moreover, we also then have proper sidebar highlighting. 
Also noticed that the sidebar highlighting …
> Fixing redirects and sidebar highlighting

- content/reference/v1beta1/config.md
Provided examples for bool, label, hidden, read-only
Fixed issues with `file` and `when` examples. 
Added spaces so that examples could be pasted into config.yaml
Noted which items aren't working right now: heading, select_many, recommended.
> Correcting a lot of problems on config.md page

- content/kotsadm/installing/system-requirements.md
- content/release-notes/1.11.0.md
- resources/_gen/assets/scss/scss/style.scss_5ad6f408b0e3e473c748aac88af0ea18.content
- themes/hugo-whisper-theme/assets/scss/pages/_home.scss
- themes/hugo-whisper-theme/layouts/_default/li.html
- themes/hugo-whisper-theme/layouts/_default/single.html
When you include the "kubernetes" label in the release notes, it also displays support k8s version.
> K8s Version Compatibility / Sys Requirements

- content/reference/v1beta1/application.md
- content/vendor/cli/_index.md
- content/vendor/config/_index.md
- content/vendor/config/application-status.md
- content/vendor/config/config-screen.md
- content/vendor/config/dashboard-buttons.md
- content/vendor/config/dashboard-graphs.md
- content/vendor/dashboard/_index.md
- content/vendor/embedded-kubernetes/_index.md
- content/vendor/entitlements/_index.md
- content/vendor/helm/_index.md
- content/vendor/packaging/_index.md
- content/vendor/packaging/embedded-kubernetes.md
- content/vendor/packaging/packaging-an-app.md
The key is the distinction between "Admin Console Configuration" and "Application Configuration," which will be more and more useful as we add more content. 
Aliases were verified. 
No content updates, just a bit of reorg.
> Rearranging some menu items on the vendor page to make things more clear, and to help with dashboard docs. 

- Makefile
There was an earlier problem where the local copy of hugo was different than what netlify used, which created problems. When I addressed that, I only included the darwin binary. We should detect the os and get the appropriate binary (whether linux or macOs). 
This way, it will work with codeserver
> Ensuring that we download a linux version of the installer when it's not darwin

- content/kotsadm/installing/system-requirements.md
We need root when doing an embedded cluster install, and we don't need root when doing an existing cluster install. We should explicitly state this.
> Explicitly mentioning root access requirements for existing cluster or embedded cluster installs

- content/reference/v1beta1/config.md
- content/vendor/guides/airgapped-cluster.md
- content/vendor/guides/ci-cd-integration.md
* Update Airgap docs to include how to use base64 image for icon.
* Removed Existing Airgap instructions.
* Updated some typos in config.
* Fixed the command in CI/CD Helm Chart.
> AirGap Base64 Icon

- content/kotsadm/registries/self-hosted-registry.md
The first part of this doc was mostly correct, just cleaned up some phrases and removed a couple of factually incorrect statements.
The second half of this doc showed an unsupported workflow. This should be rewritten in 1.17 with the new aigap existing cluster feature.
> Remove and update registry docs

- content/kotsadm/installing/system-requirements.md
- content/reference/template-functions/static-context.md
- content/reference/v1beta1/config.md
- Document how `RandomString` behaves based on `hidden` and `readonly` fields.
-  `help_text` docs were missing and clarified usage of `description`.
- Also added a note that both support Markdown syntax.
- Updated KOTS-K8s compatibility matrix.
> Hidden vs. Readonly Properties

- content/release-notes/1.18.0.md
Was previously: 
> Fixed a bug that caused kots install ... --config <filename> command ignore valuePlaintext in password fields in the supplied config file.
Changed to fix the grammar and to make it clear what the negative impact is
> Fixing wording for issue with encryption and `kots install`

- content/reference/template-functions/license-context.md
Had to dig through source of the template function as well as the REST API to figure out allowed values, figured I'd save others work by documenting them.
> Add note to LicenseFieldValue about allowed vals

- content/vendor/guides/airgapped-existing-cluster.md
* Updated the kURL addon URL to a new one which includes EKCO. I don't want to terminate this setup because it was time consuming to set it up, rather I just want to stop the nodes when I'm not using them.
* Updated the `plain-registry.yaml` URL to the replicated-automation repo so it reads a little easier than the hash. PR here https://github.com/replicatedhq/replicated-automation/pull/15
* Showed an example of how success vs. error looks like when testing the registry. Also the screenshot of the docker config was small so it wasn't clear how the syntax was supposed to be, so instead added the JSON blob.
> Update Airgap Existing Guide

- content/vendor/helm/optional-charts.md
Without quotes, exclude will fail linting
> Tiny PR: exclude needs quotes

- content/release-notes/1.25.0.md
clarify embedded support only now vs existing cluster
> clarify embedded support in 1.25.0

- content/release-notes/1.26.0.md
clarify embedded support only now vs existing cluster
> clarify embedded support in 1.26.0

- content/kotsadm/installing/system-requirements.md
Looking at the docs, we hadn't updated this chart since the v1.20 release. Adding a line with each release makes it easy to get outdated, and it gets really long if we release frequently. I updated to a format that still conveys the info, but should be easier to maintain while taking up less content area.
> make k8s version compatibility chart more scalable

- content/vendor/packaging/customers-and-licenses.md
> Removed words that imply expired license can stop running applications

- content/vendor/cli/release create.md
Removed documentation mentioning an unsupported `--required` flag.
Also added clear command line examples for all supported `release create` CLI flags.
> Removed unsupported flag / added examples for all valid options

- content/kots-cli/install.md
- content/kots-cli/pull.md
- content/kotsadm/installing/helm-chart.md
```
~$ kubectl kots pull helm://elastic/elasticsearch --helm-version v3
• Pulling upstream ✓  
• Creating base ✓  
• Creating midstream ✓  
Kubernetes application files created in /home/user/elasticsearch
To deploy, run kubectl apply -k /home/user/elasticsearch/overlays/midstream
```
> Fix helm pull command

- content/kots-cli/admin-console/generate-manifests.md
[CH36021](https://app.clubhouse.io/replicated/story/36021/a-cli-command-or-a-flag-for-the-kots-pull-command-to-generate-only-the-admin-console-components-as-kustomizable-yaml-manifests)
> document generate-manifests command

- content/kots-cli/pull.md
I used this one as a template for `kots admin-console generate-manifests` and noticed it didn't follow our contribution guidelines.
> update kots pull to match contribution guidelines

- content/vendor/cli/getting-started.md
- content/vendor/cli/tokens.md
User tokens cannot be used in CLI commands hitting GraphQL.  GraphQL does not enforce any RBAC and will not check for hashed user tokens.
> updating token docs

- content/kots-cli/backup/_index.md
- content/kots-cli/download.md
- content/kots-cli/restore/_index.md
- content/kots-cli/upload.md
- content/kots-cli/upstream.md
[CH33701](https://app.clubhouse.io/replicated/story/33701/kots-cli-add-output-formatting-option-for-json-and-status-field-if-possible)
> [1.50.0] docs: add output flag to relevant cli cmds

- content/vendor/packaging/include-resources.md
Removed imaginary annotation called 'kots.io/include':  and replaced it with 'kots.io/when'
> Removed imaginary annotation called 'kots.io/include':  and replaced it with 'kots.io/when' 

- content/reference/v1beta1/config.md
- content/vendor/packaging/template-functions.md
Screen cap of the warning box:
> fix: clarify ephemeral behavior of ConfigItem defaults
